# Generated by Django 4.2.7 on 2025-06-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
